PDQ - scheletro + inizio
DreamTeamSWE/Documenti pull request #18
Opened 2021-12-08 12:17 UTC by francescoo22

2021-12-08 12:31 UTC, francescoo22 commented
manca il file .pdf

2021-12-09 22:39 UTC, Pitora approved these changes
Da togliere quel verificatore e cambiare l'uso del documento che è esterno.  Per il resto va bene.

2021-12-09 23:59 UTC, mikigatto93 requested changes
Vedi commenti

2021-12-09 23:59 UTC, mikigatto93 commented on PianoDiQualifica/Sezioni/Introduzione.tex
> +Il documento definirà inoltre le modalità di validazione e verifica al fine di evitare che venga effettuata una verifica di tipo retrospettivo permettendo così di poter rilevare e correggere errori i
Toglierei questo perché comunque una parte di verifica retrospettiva devi farla, qualcosa del genere: "Il documento definirà quindi un sistema di di validazione e verifica continua che permetterà di rilevare e correggere andamenti indesiderati e/o anomalie il prima possibile, con l'aspettativa finale di una riduzione degli sprechi di risorse e di una manutenzione più semplice"

2021-12-09 23:59 UTC, mikigatto93 commented on PianoDiQualifica/Sezioni/Introduzione.tex
> +L’obiettivo di Sweeat dell’azienda Zero12 è la creazione di un sistema software costituito da un’applicazione mobile e da una webapp. Lo scopo del prodotto è di fornire all’utente una guida dei local
ennesima proposta di modifica allo scopo (sorry). Semplicemente la prima frase metterei: "Lo scopo del nostro prodotto, denominato SWEEAT, è la creazione di un sistema software di web crawling e analisi dei dati  fornendo all utente (tramite web app o mobile app) una guida ...." 
il prodotto è nostro quindi toglierei dell'azienda zero12 che l ha solo proposto.

2021-12-09 23:59 UTC, mikigatto93 commented on PianoDiQualifica/Sezioni/RegistroModifiche.tex
> +	1.0.0& XX.12.21& \shortstack{ \\ XX} &\shortstack{ \\ \RE{} } & Approvazione per il rilascio\\
Per il registro delle modifiche farei una sola riga con i vostri tre nomi e  descrizione qualcosa tipo: "realizzazione scheletro latex e stesura introduzione" v0.0.1 e poi scrivere i nomi dei verificatori (colonna aggiuntiva o tra parentesi sulla descrizione ?) così riflette la pull request della sua modifica e rappresenta uno scatto verificato.

2022-01-04 20:35 UTC, mikigatto93 approved these changes

2022-01-04 20:35 UTC, merged